Draft: Add HCL config
avenga/couper pull request #140
Opened 2021-03-12 10:19 UTC by alex-schneider

2021-05-04 07:08 UTC, malud submitted a review, later dismissed

2021-05-04 07:19 UTC, filex requested changes

2021-05-04 07:19 UTC, filex commented on docs/ERRORS.md
> +  # Behaves like an endpoint
this important info should also be in the explaining text (outside of the code snippet)

2021-05-04 07:19 UTC, filex commented on docs/ERRORS.md
> +Especially some access-control errors are expected ones and may be handled on a specific manner.
```suggestion
Especially some access-control errors are expected to occur and may need special handling, e.g. sending a specific response for missing login credentials.
```

2021-05-04 07:19 UTC, filex commented on docs/ERRORS.md
> +# Without label will catch all validation errors related to this access control.
this important info should also be in the explaining text (outside of the code snippet)

2021-05-04 07:19 UTC, filex commented on docs/ERRORS.md
> +| Type                              | Description |
should we add a column for the `Standard handling`? "Send error template with 401", "Send error template with 403" …

2021-05-05 11:27 UTC, malud approved these changes

2021-05-05 11:28 UTC, merged