OAuth2 Authorization Code Grant Flow
avenga/couper pull request #247
Opened 2021-05-26 07:20 UTC by johakoch

2021-06-14 08:38 UTC, johakoch commented
Im Moment ist es so implementiert, dass erwartet wird, dass Code-Verifier oder CSRF-Token als solche an den Browser gehen: Im Request an den Redirekt-Endpunkt müssen sie aus dem Request ermittelbar sein (z.B. im Cookie). Dafür gibt es die Konfigurations-Attribute `code_verifier_value` und `csrf_token_value`:
```hcl
oauth2 "my-ac" {
  ...
  code_verifier_value = request.cookies.cv
#  csrf_token_value = request.cookies.ct
  ...
}
```
Ohne einen zentralen Store ist es dann auch wahrscheinlich, dass Access-/Id-/Refresh-Tokens als solche (als Cookie) im Browser gespeichert werden. Hätte man einen (von verschiedenen Couper-Instanzen verwendeten) zentralen Store, könnte man die Tokens selbst im Store speichern und nur eine Referenz darauf an den Browser gehen. Das würde ggfs. die Sicherheit noch erhöhen.
Ebenso könnten dann Code-Verifier/CSRF-Token selbst im Store verbleiben und nur Referenzen darauf an den Browser gehen.
Verbaut man sich nun durch die genannten Konfigurations-Attribute eine mögliche Erweiterung durch einen zentralen Store? Vermutlich nicht: `code_verifier_value`/`csrf_token_value` müssten dann nur anders interpretiert werden, nämlich als Referenzen auf die eigentlichen Werte. Welche Variante gewünscht ist, ließe sich sicherlich konfigurativ ausdrücken.

2021-06-16 07:38 UTC, filex commented
> Verbaut man sich nun durch die genannten Konfigurations-Attribute eine mögliche Erweiterung durch einen zentralen Store? Vermutlich nicht: `code_verifier_value`/`csrf_token_value` müssten dann nur anders interpretiert werden, nämlich als Referenzen auf die eigentlichen Werte. Welche Variante gewünscht ist, ließe sich sicherlich konfigurativ ausdrücken.

The current idea is, that `code_verifier_value` is defined as an arbitrary expression that usually involves cookies. if we would incorporate a KV interface, we could provide a lookup function as a simple solution. That would still fit the expression approach.

But I would rather make that token store a built-in feature that is configured outside of the AC. We could then reference it with a new set of config attributes that are mutually exclusive with `code_verifier_value`.

For the task here, I agree that we can proceed with the value-approach.

2021-06-16 15:11 UTC, malud requested changes
First go related feedback.

2021-06-16 15:11 UTC, malud commented on handler/transport/oauth2.go
> +	url, err := eval.GetContextAttribute(oa.config.HCLBody(), outCtx, "token_endpoint")
I know, was `url` before but this variable name collides with import package.

2021-06-16 15:11 UTC, malud commented on utils/base64url/base64url.go
> +package base64url
Some reading: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

Just place this next to jkws.

Yep, `utils` are there but will be removed in the future.

2021-06-16 15:57 UTC, malud commented on accesscontrol/jwks.go
> +func (j JWKS) Key(kid string) []JWK {
Ok its more a find, but GetKeys would be ok ;)

2021-06-17 07:17 UTC, malud commented on eval/context.go
> +func (c *Context) updateFunctions() {
Does oauth2 functions depending on `ctx.eval` like `JwtSignFunction` ? Seems to be obsolete recreate those ones every time? (maybe saml too). Inline Attrs gets referenced just from the AccessControl side with current context. We should prefer splitting setup and update functions.

2021-06-24 07:14 UTC, malud requested changes
Some things to do, please see the comments from last week.

2021-06-24 07:14 UTC, malud commented on handler/transport/oauth2_req_auth.go
> +// NewOAuth2 creates a new <http.RoundTripper> object.
```suggestion
// NewOAuth2ReqAuth creates a new <http.RoundTripper> object.
```

2021-06-24 07:14 UTC, malud commented on server/http_oauth2_test.go
> +			helper.Must(err)
create new subtest helper with `subT`

2021-06-24 07:14 UTC, malud commented on server/http_oauth2_test.go
> +					t.Errorf("%q: expected params %s, got: %s", tc.name, tc.params, params)
```suggestion
					subT.Errorf("%q: expected params %s, got: %s", tc.name, tc.params, params)
```

applies to all `t`'s .

2021-06-24 09:15 UTC, johakoch commented on accesscontrol/oauth2.go
> +	requestConfig.Code = &code
As `GetRequestConfig()` is used by both `accesscontrol.OAuth2Callback` and `transport.OAuth2ReqAuth` and this is specific to the AC flow, I would rather keep it here.

2021-06-24 09:36 UTC, johakoch commented on accesscontrol/oauth2.go
> +		return errors.Oauth2.Messagef("wrong method: %s", req.Method)
Should the caller give the context? Or the callee?

2021-06-24 09:50 UTC, johakoch commented on accesscontrol/oauth2.go
> +func (oa *OAuth2Callback) validateIdTokenClaims(claims jwt.Claims, csrfToken, csrfTokenValue string, ctx context.Context, accessToken string) (map[string]interface{}, error) {
Now, that the userinfo requst is back, these variables are used again. I moved `ctx` to first place.

2021-06-25 17:13 UTC, merged