Oauth 2.0: Locking for token requests
avenga/couper pull request #270
Opened 2021-07-05 09:27 UTC by alex-schneider

2021-07-29 14:08 UTC, malud requested changes

2021-07-30 11:37 UTC, afflerbach commented on handler/transport/oauth2_req_auth.go
> +type locks map[string]*sync.Mutex
Done.

2021-08-03 07:37 UTC, malud requested changes
LGTM; except -> missing Changelog entry

2021-08-05 15:13 UTC, malud approved these changes

2021-08-05 15:14 UTC, merged