OIDC
avenga/couper pull request #273
Opened 2021-07-20 10:14 UTC by johakoch

2021-07-20 10:20 UTC, johakoch commented
New **Beta** feature: `beta_oidc` block for configuring OIDC (authorization code flow).

2021-07-29 12:16 UTC, malud requested changes

2021-07-29 12:16 UTC, malud commented on config/oidc.go
> +type OpenidConfiguration struct {
This object, the related obj `OidcConfig` and logic to retrieve the configuration data should be moved to the `oauth2` package. Its to just to much non hcl/configload related context.

2021-07-29 12:16 UTC, malud commented on oauth2/oauth2.go
> +// NewOAuth2AC() creates a new OAuth2 Authorization Code client.
```suggestion
// NewOAuth2AC creates a new OAuth2 Authorization Code client.
```

2021-07-30 09:54 UTC, malud requested changes

2021-07-30 09:54 UTC, malud commented on eval/lib/oauth2.go
> +			query.Set("redirect_uri", *oauth2.GetRedirectURI())
GetRedirectURI() should return a dereferenced string.

2021-07-30 10:37 UTC, malud approved these changes

2021-07-30 10:37 UTC, merged