Add websockets support
avenga/couper pull request #280
Opened 2021-08-04 12:51 UTC by alex-schneider

2021-08-10 06:04 UTC, malud requested changes

2021-08-10 06:04 UTC, malud commented on eval/context.go
> +		if !CheckUpgradeResponse(bereq, beresp) {
Also a comment line would be nice within this context to note why reading the body should be skipped.

2021-08-10 06:04 UTC, malud commented on handler/proxy.go
> +	if p.allowWebsockets {
As already said: dynamic value

2021-08-20 06:14 UTC, malud requested changes

2021-08-20 06:14 UTC, malud commented on config/websockets.go
> +		SetRequestHeaders map[string]string `hcl:"set_request_headers,optional"`
What about `set_response_headers` ? Could get registered via responseWriter modifier.

2021-08-20 06:14 UTC, malud commented on docs/REFERENCE.md
> +The `websockets` block activates support for websocket connection in Couper.
```suggestion
The `websockets` block activates support for websocket connections in Couper.
```

2021-08-20 06:14 UTC, malud commented on handler/proxy.go
> +	if wss := content.Blocks.OfType("websockets"); len(wss) == 1 {
extract this block into a method.

2021-08-20 06:14 UTC, malud commented on config/configload/load.go
> +				if proxyRequestLabelRequired || endpoint.Response != nil {
I recommend to review https://github.com/avenga/couper/pull/294 beforehand.

2021-08-23 07:41 UTC, alex-schneider commented on config/request/context_key.go
> +	AllowWebsockets
We can do it later if necessary...

2021-08-24 07:39 UTC, malud requested changes
Some things:

- [x] applyWebsockets method complexity can be reduced
- [ ] `set_response_headers` within `websockets` does not work at all
- [x] missing test for `set_response_headers`
- [x] apply context order must be: proxy body, proxy blacklist, websockets body
- [x] without order fixup, `set_request_headers = { cookie = request.headers.cookie }` does not work

2021-08-24 07:39 UTC, malud commented on handler/proxy.go
> +	if wss := bodyContent.Blocks.OfType("websockets"); len(wss) == 1 {
```suggestion
	wss := bodyContent.Blocks.OfType("websockets")
	if len(wss) != 1 {
		return nil
	}
```

reduce method complexity

2021-08-24 07:39 UTC, malud commented on handler/proxy.go
> +		if eval.IsUpgradeRequest(req) {
also early out

2021-08-24 07:39 UTC, malud commented on handler/proxy.go
> +			if attr, ok := bodyContent.Attributes["timeout"]; ok {
also early out, without timeout just return `nil`.

2021-08-24 07:39 UTC, malud commented on config/request/context_key.go
> +	AllowWebsockets
Take a look at the existing ones. We have a convention already:

Endpoint*
RoundTrip*
TokenRequest*

so a good fit would be
WebsocketsAllowed/Enabled
WebsocketsTimeout

2021-08-25 08:11 UTC, alex-schneider commented on server/writer/response.go
> +	writeStatusCode := statusCode
Why this new var?

2021-08-25 08:13 UTC, alex-schneider commented on server/writer/response.go
> +	brw.Writer.Reset(r)
panic() candidate if err != nil

2021-08-25 11:02 UTC, malud approved these changes

2021-08-25 11:07 UTC, merged