sequence
avenga/couper pull request #405
Opened 2021-12-03 17:05 UTC by malud

Determine a possible sequence of roundtrips due to variable references.

atm broken with proxies

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

2021-12-10 12:06 UTC, johakoch commented on server/http_endpoints_test.go
> +		if strings.Contains(entry.Message, context.Canceled.Error()) {
```suggestion
		path, _ := entry.Data["request"].(logging.Fields)["path"]

		if strings.Contains(entry.Message, context.Canceled.Error()) {
```

2021-12-10 12:08 UTC, johakoch commented on server/http_endpoints_test.go
> +		}
```suggestion
		path, _ := entry.Data["request"].(logging.Fields)["path"]

		if strings.Contains(entry.Message, context.Canceled.Error()) {
			ctxCanceledSeen = true
			if path != "/" {
				t.Errorf("expected '/' to fail")
			}
		}

		if entry.Message == "" && entry.Data["status"] == 200 {
			statusOKseen = true
			if path != "/reflect" {
				t.Errorf("expected '/reflect' to be ok")
			}
		}
```

2021-12-10 12:09 UTC, johakoch commented on server/http_endpoints_test.go
> +		}
```suggestion
		path, _ := entry.Data["request"].(logging.Fields)["path"]

		if entry.Message == "backend timeout error: deadline exceeded" {
			ctxDeadlineSeen = true
			if path != "/" {
				t.Errorf("expected '/' to fail")
			}
		}

		if entry.Message == "" && entry.Data["status"] == 200 {
			statusOKseen = true
			if path != "/reflect" {
				t.Errorf("expected '/reflect' to be ok")
			}
		}
```

2021-12-10 12:09 UTC, johakoch commented on server/http_endpoints_test.go
> +		}
Needs
```
	"github.com/avenga/couper/logging"
```

2021-12-10 12:18 UTC, malud commented on server/http_endpoints_test.go
>  	"github.com/avenga/couper/internal/test"
```suggestion
	"github.com/avenga/couper/internal/test"
	"github.com/avenga/couper/logging"
```

2021-12-10 13:32 UTC, johakoch commented on config/runtime/endpoint.go
> +func newSequence(proxies map[string]*producer.Proxy, requests map[string]*producer.Request, errCh chan<- error,
rename to `newSequences()`, as it creates `producer.Sequences` (plural)

2021-12-10 17:08 UTC, johakoch commented on docs/REFERENCE.md
> +| `expected_status`       | list<number> | -       | If defined, the [Backend Block](#backend-block) response status code will be verified against this list of codes. If the status-code is unexpected
```suggestion
| `expected_status`       | list<number> | -       | If defined, the response status code will be verified against this list of codes. If the status-code is unexpected an [`unexpected_status` error](./ERRORS.md#error-types) can be handled with an [`error_handler`](./ERRORS.md#endpoint-related-error_handler). | -                                                                                      | -                   |
```

2021-12-10 17:09 UTC, johakoch commented on docs/REFERENCE.md
> +| `expected_status` | list<number>                          | -       | If defined, the [Backend Block](#backend-block) response status code will be verified against this list of codes. If the status
```suggestion
| `expected_status` | list<number>                          | -       | If defined, the response status code will be verified against this list of codes. If the status-code is unexpected an [`unexpected_status` error](./ERRORS.md#error-types) can be handled with an [`error_handler`](./ERRORS.md#endpoint-related-error_handler). | -                                                                                                                                                                                      | -                 |
```

2021-12-13 16:01 UTC, johakoch commented on handler/transport/backend_test.go
> +	t.Skip("TODO: test-hook to obtain values")
Needs resolve

2021-12-21 09:26 UTC, johakoch commented on config/runtime/server.go
> +			acBodies := bodiesWithACBodies(conf.Definitions, endpointConf.AccessControl, endpointConf.DisableAccessControl)
Why is this renamed to `acBodies`?

2021-12-21 09:30 UTC, johakoch commented on config/runtime/server.go
> +		serverBodies = append(serverBodies, srvConf.HCLBody())
Why `srvConf.HCLBody()` instead of `srvConf.Remain`, etc.?

2021-12-21 12:33 UTC, johakoch requested changes

2021-12-21 12:33 UTC, johakoch commented on docs/ERRORS.md
> +TBA
docu missing yet

2021-12-21 12:33 UTC, johakoch commented on config/configload/load.go
> +	"github.com/hashicorp/hcl/v2"
fix order of imports:
```
	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/gohcl"

	"github.com/avenga/couper/config"
	...
```

2021-12-21 12:58 UTC, johakoch submitted a review, later dismissed

2021-12-21 13:16 UTC, johakoch approved these changes

2021-12-21 13:17 UTC, merged