Add logging for endpoint sequence items
avenga/couper pull request #411
Opened 2021-12-22 15:41 UTC by malud

Log previous sequence item name

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

2022-01-03 11:03 UTC, johakoch requested changes

2022-01-04 07:30 UTC, malud commented on server/http_endpoints_test.go
> +					st.Errorf("Expected 'depends_on' log field value: %q, got: %q", "a", dependsOn)
Applied fixup from https://github.com/avenga/couper/pull/414/files#diff-bb0e314ec16a1e34652e432d19067d848b81e2e975612357babb52e8c4a7d8edR543

2022-01-04 11:31 UTC, malud commented on server/http_endpoints_test.go
> +					continue
I got your point but this means listing all possible defined be-requests within the expectation struct, some kind of mirroring the config even those which are not part of the sequence (stand-alones). Possible but would result in a way more complicated test. How a configuration with an unexpected request would look like?
Unexpected deps should be covered with the `depends_on` check ?

2022-01-04 15:42 UTC, johakoch commented on server/http_endpoints_test.go
> +					continue
e.g. in the last case, only depencies for requests default and resolve are expected. Other requests (standalone depends on resolve_first, resolve_gamma depends on resolve_gamma_first) are ignored; no `depends_on` check is performed for these.

2022-01-05 10:31 UTC, johakoch approved these changes

2022-01-05 10:31 UTC, merged