JWT: Set `private` directive to the CC header
avenga/couper pull request #418
Opened 2022-01-10 08:49 UTC by alex-schneider

Automatically add the `private` directive to the response `Cache-Control` HTTP header field value for all resources protected by JWT.

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

2022-01-10 14:52 UTC, johakoch requested changes

2022-01-10 14:52 UTC, johakoch commented on server/http_endpoints_test.go
> +			// Prevent diff errors from an unordered list.
Better create an _additional_ test (e.g. in http_integration_test.go, where several JWT tests already reside) than "hijack" the test named TestEndpointACBufferOptions to check for something very difference.

2022-01-10 16:53 UTC, johakoch requested changes

2022-01-10 16:53 UTC, johakoch commented on docs/REFERENCE.md
> +| `disable_private_caching` | bool | `false` | If set to `true`, Couper does not add the `private` directive to the `Cache-Control` HTTP header field value. | - | - |
The new default behaviour (adding `private`) should be documented in prose in the section on JWT; not only the possibility to change this default using this attribute.

2022-01-10 16:53 UTC, johakoch commented on config/runtime/server.go
> +					Algorithm:             jwtConf.SignatureAlgorithm,
possible improvement:
* create `&ac.JWTOptions{...}` with members used in **both** cases outside the `if`
* set the members specific to the case (`if` / `else`) and then call `ac.NewJWTFromJWKS()` / `ac.NewJWT()` with the modified `JWTOptions`

So there will be a lower probability that a new common member is added in only one of the cases

2022-01-11 11:52 UTC, malud requested changes

2022-01-11 11:52 UTC, malud commented on CHANGELOG.md
> +  * `disable_private_caching` attribute for the [JWT Block](./docs/REFERENCE.md#jwt-block) ([#418](https://github.com/avenga/couper/pull/418))
Changelog rebase required (-> unreleased)

2022-01-25 08:44 UTC, malud approved these changes

2022-01-25 08:44 UTC, merged