channels for sequences
avenga/couper pull request #684
Opened 2023-01-31 10:09 UTC by johakoch

use channels to pass (error) results to and receive results from proxies/requests

Describe your changes!

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

2023-02-01 08:19 UTC, johakoch commented
I don't think, we need a changelog entry here.
@malud please, have a look.

2023-03-27 15:59 UTC, malud requested changes
LGTM, just one more func. Even client cancels seems to work as expected.

2023-03-28 07:29 UTC, malud commented
Hm unstable tests.

```
=== RUN   TestJWKsMaxStale
http_integration_test.go:3621: expected status 200, got: 401 ()
RUN   TestOpenAPIValidator_RelativeServerURL
openapi_test.go:138: backend error: status is not supported
```

Also the openApi test failure I have already seen on this branch.

2023-03-29 06:40 UTC, malud approved these changes

2023-03-29 06:40 UTC, merged