Deprecations
avenga/couper pull request #734
Opened 2023-02-28 09:39 UTC by alex-schneider

Describe your changes!

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

2023-03-01 15:43 UTC, malud commented
Please revert the commit https://github.com/avenga/couper/pull/734/commits/5b924b7e7d762072d6b6cad68ce7725b0641bb7c since its changes almost 20 func calls to use an empty argument to get rid of 3 lines of code.

2023-03-03 10:52 UTC, johakoch commented on config/configload/deprecated_test.go
> +	"github.com/hashicorp/hcl/v2/hclsyntax"
```suggestion
	"github.com/google/go-cmp/cmp"
	"github.com/hashicorp/hcl/v2/hclsyntax"

	"github.com/avenga/couper/config/parser"
	"github.com/avenga/couper/internal/test"
```

2023-03-10 10:38 UTC, malud requested changes

2023-03-10 10:38 UTC, malud commented on config/configload/deprecated.go
> +		logger.Warn(fmt.Sprintf(
`Warnf` should do the trick here. Also lower case the log message.

2023-03-10 10:38 UTC, malud commented on config/configload/deprecated.go
> +		logger.Warn(fmt.Sprintf(
adapt related tests

2023-03-10 11:27 UTC, malud approved these changes

2023-03-10 11:28 UTC, merged